spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_portal
    username: postgres
    password: 3884
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket: lms-storage


security:
  jwt:
    secret-key: ZridVCrtqhCWNa1sfOEEAKrreshnNNfQ31VmVpBQT9u7+V1/qYETw/GMksOlhwvk2KeT/3jpg8aYJvTlba4gIjvna2og+3FdOHpQmXOVzDx2n4oIB+mQ9kj/kxiwLP80P/PUaymTD+szhgAG2N7AZZP/A9iSoRxCK6aX3Dmsg5M=
    access-token-expiration: 3600000
    refresh-token-expiration: 604800000
    issuer: "https://student.system.uz"
